apiVersion: v1
kind: Service
metadata:
 name: flask-app
spec:
 type: ClusterIP
 selector:
  app: task1-app
 ports:
  - protocol: TCP
    port: 5500
    targetPort: 5500

---

apiVersion: apps/v1
kind: Deployment
metadata: 
 name: task1-app
 labels:
  app: task1-app
spec:
  strategy: 
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  selector: 
    matchLabels:
      app: task1-app
  replicas: 2
  template: 
    metadata:
       labels:
         app: task1-app
    spec:
      containers:
      - name: task1-app
        image: satishgssk/task1-app:v{{version}}
        env:
        - name: YOUR_NAME
          value: {{userName}}

  
   
 
