apiVersion: v1
kind: Service
metadata:
 name: task1-nginx
spec:
 type: LoadBalancer
 selector:
  app: task1-nginx
 ports:
  - protocol: TCP
    port: 80

---

apiVersion: v1
kind: Pod
metadata: 
 name: task1-nginx
 labels:
  app: task1-nginx
spec:
  volumes:
  - name: task1-nginx-vol
    configMap: 
      name: task1-nginx-config
  containers:
  - name: task1-nginx
    imagePullPolicy: IfNotPresent
    image: nginx:alpine
    volumeMounts:
    - name: task1-nginx-vol
      mountPath: /etc/nginx

---

apiVersion: v1
kind: ConfigMap
metadata: 
  name: task1-nginx-config
data: 
  nginx.conf: |
    events {}
    http {
    server {
        listen 80;
        location / {
            proxy_pass http://flask-app:5500;
        }
      }
    }
   
 
