apiVersion: v1
kind: Service
metadata:
 name: flask-app
spec:
 type: LoadBalancer
 selector:
  app: task1-app
 ports:
  - protocol: TCP
    port: 5500
    targetPort: 5500

---

apiVersion: v1
kind: Pod
metadata: 
 name: task1-app
 labels:
  app: task1-app
spec:
  containers:
  - name: task1-app
    imagePullPolicy: IfNotPresent
    image: satishgssk/task1-python-img
    ports: 
     - containerPort: 5500
    env:
    - name: YOUR_NAME
      value: Sathish-nginx
  
   
 
